// github-api.js - Using locally stored GitHub data with fallback to API

(function() {
  const GITHUB_USERNAME = 'xurst';
  const GITHUB_API_BASE = 'https://api.github.com';
  
  // First try to load data from local JSON files generated by GitHub Actions
  // If that fails, fall back to the GitHub API with caching
  
  // Use localStorage for caching to reduce API calls
  const cache = {
    set: function(key, data, ttl = 3600000) { // Default TTL: 1 hour
      const item = {
        data: data,
        expiry: Date.now() + ttl
      };
      localStorage.setItem(`gh_cache_${key}`, JSON.stringify(item));
    },
    get: function(key) {
      const item = localStorage.getItem(`gh_cache_${key}`);
      if (!item) return null;
      
      const parsedItem = JSON.parse(item);
      if (Date.now() > parsedItem.expiry) {
        localStorage.removeItem(`gh_cache_${key}`);
        return null;
      }
      
      return parsedItem.data;
    },
    clear: function() {
      Object.keys(localStorage)
        .filter(key => key.startsWith('gh_cache_'))
        .forEach(key => localStorage.removeItem(key));
    }
  };
  
  // Helper function to load local JSON files
  async function loadLocalData(file) {
    try {
      const response = await fetch(`/data/${file}`);
      if (!response.ok) {
        throw new Error(`Failed to load ${file}`);
      }
      return await response.json();
    } catch (error) {
      console.warn(`Local data file (${file}) not found or invalid, falling back to API`);
      return null;
    }
  }
  
  // Centralized fetch function with caching and error handling
  async function fetchFromGitHub(endpoint, options = {}) {
    // Try loading from local data files first
    if (endpoint === `/users/${GITHUB_USERNAME}/repos`) {
      const localData = await loadLocalData('repositories.json');
      if (localData) {
        console.log('Using local repositories data');
        return localData;
      }
    } else if (endpoint.includes('/languages')) {
      // Languages are already embedded in the local repo data
      // This is handled in getRepoLanguages function
    }
    
    // If local data is not available, try the API with caching
    const url = endpoint.startsWith('http') ? endpoint : `${GITHUB_API_BASE}${endpoint}`;
    const cacheKey = endpoint.replace(/[^a-zA-Z0-9]/g, '_');
    
    // Check cache first
    const cachedData = cache.get(cacheKey);
    if (cachedData) {
      console.log(`Using cached data for ${endpoint}`);
      return cachedData;
    }
    
    // Set up headers
    const headers = new Headers({
      'Accept': 'application/vnd.github.v3+json'
    });
    
    const requestOptions = {
      ...options,
      headers
    };
    
    try {
      const response = await fetch(url, requestOptions);
      
      // Handle rate limiting
      if (response.status === 403) {
        const rateLimitRemaining = response.headers.get('X-RateLimit-Remaining');
        if (rateLimitRemaining === '0') {
          const resetTime = new Date(parseInt(response.headers.get('X-RateLimit-Reset')) * 1000);
          throw new Error(`GitHub API rate limit exceeded. Resets at ${resetTime.toLocaleTimeString()}`);
        }
      }
      
      if (!response.ok) {
        throw new Error(`GitHub API error: ${response.status} - ${response.statusText}`);
      }
      
      const data = await response.json();
      
      // Cache the results
      cache.set(cacheKey, data);
      
      return data;
    } catch (error) {
      console.error(`Error fetching ${url}:`, error);
      throw error;
    }
  }
  
  // Helper function to retry failed requests
  async function fetchWithRetry(endpoint, options = {}, maxRetries = 2) {
    let retries = 0;
    
    while (retries < maxRetries) {
      try {
        return await fetchFromGitHub(endpoint, options);
      } catch (error) {
        retries++;
        
        if (retries >= maxRetries) {
          throw error;
        }
        
        const delay = Math.pow(2, retries) * 1000; // Exponential backoff
        console.log(`Retrying in ${delay}ms... (${retries}/${maxRetries})`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
  }
  
  // Special function for getting repo languages
  async function getRepoLanguages(repoName) {
    // First check if we have local repository data with embedded languages
    try {
      const repos = await loadLocalData('repositories.json');
      if (repos) {
        const repo = repos.find(r => r.name === repoName);
        if (repo && repo.languages) {
          console.log(`Using local language data for ${repoName}`);
          return repo.languages;
        }
      }
    } catch (error) {
      console.warn('Error loading local language data, falling back to API');
    }
    
    // Fall back to API call
    return fetchWithRetry(`/repos/${GITHUB_USERNAME}/${repoName}/languages`);
  }
  
  // Function to get featured repos
  async function getFeaturedRepos() {
    // Try to load from featured-repositories.json first
    const featuredRepos = await loadLocalData('featured-repositories.json');
    if (featuredRepos) {
      console.log('Using local featured repositories data');
      return featuredRepos;
    }
    
    // Fall back to fetching all repos and sorting by stars
    const repos = await fetchWithRetry(`/users/${GITHUB_USERNAME}/repos`);
    return repos
      .filter(repo => !repo.fork)
      .sort((a, b) => b.stargazers_count - a.stargazers_count)
      .slice(0, 4);
  }
  
  // Expose functions to global context
  window.GitHubAPI = {
    username: GITHUB_USERNAME,
    fetchFromGitHub,
    fetchWithRetry,
    getUserRepos: () => fetchWithRetry(`/users/${GITHUB_USERNAME}/repos`),
    getRepoDetails: (repoName) => fetchWithRetry(`/repos/${GITHUB_USERNAME}/${repoName}`),
    getRepoLanguages,
    getFeaturedRepos,
    clearCache: () => cache.clear()
  };
})();